### ISSUE TITLE
Hierarchy Entity Issue

### ISSUE THREAD

**Issue by DiggaTheWolf** [LinkeD365/ERDVisioBuilder#11]
When including the Product Catalogue an exception is generated stating 'cannot connect shape to itself', I've attached the full exception output. The entities I included were Product, Unit Group, Unit, Price List and Price List Item. Level set to 1 and Only Between Selected Entities checked. When the exception is generated, I dismiss the notification and hit the Create Visio button again to get the file saved.

[ERDVisioBuilder.Exception.Hierarchy.txt](https://github.com/LinkeD365/ERDVisioBuilder/files/5486329/ERDVisioBuilder.Exception.Hierarchy.txt)

**Comment by LinkeD365** [comment]
THanks @DiggaTheWolf I have moved the enhancement out. Got a little time later in the week, so will take a look at both.

Cheers

**Comment by LinkeD365** [comment]
Hey @DiggaTheWolf I am struggling to repro the issue. Can you check the version? I think I have reproduced the steps. Can you confirm the version you are on?

![image](https://user-images.githubusercontent.com/43988771/98235115-4976b980-1f59-11eb-94cf-084c2e5ec98b.png)

![image](https://user-images.githubusercontent.com/43988771/98235204-6d39ff80-1f59-11eb-975b-4414a4154bfa.png)

**Comment by DiggaTheWolf** [comment]
Sure @LinkeD365 - ERD Visio Builder version 1.2020.8.1 and XrmToolBox version 1.2020.10.41

![image](https://user-images.githubusercontent.com/16100407/98240870-ffde9c80-1f61-11eb-876b-1110de490ed9.png)

![image](https://user-images.githubusercontent.com/16100407/98241025-39170c80-1f62-11eb-8434-0888f0f04e4b.png)

**Comment by DiggaTheWolf** [comment]
If you can't replicate the behaviour, then don't worry about it. It could have more to do with our customisation's which are throwing out your plugin than your plugin failing. If you want to pursue this further and if you need anything else from me, please let me know.

**Comment by LinkeD365** [comment]
Hey @DiggaTheWolf there might be an issue with many to many between same entity, resolved in latest I hope
