### ISSUE TITLE
Visio is not being created and just errors

### ISSUE THREAD

**Issue by SH-EDI** [LinkeD365/ERDVisioBuilder#14]
Is there a limit to the number of Entities that you can select?
The tool is not letting me save my config of selected Entities which takes a long time to recreate as there are 322 Entities selected.  When I select the Create Visio icon it just errors as below:
![image](https://user-images.githubusercontent.com/79582182/109002783-8ef0fb00-769e-11eb-9979-8671b89947d4.png)
I need the Visio to allow me to identify all the relationships within our CRM applicatiion.
I tried it with just 3 Entities selected and it worked fine.
---
- Deployment: Online
- DB Version: 9.2.21013.146
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.1.44
- Tool Version: 1.2020.11.1

**Comment by LinkeD365** [comment]
@SH-EDI Is there any log files produced for this error?

**Comment by LinkeD365** [comment]
THink I have found the bug. Was this a fresh install? Anyway, can you try with the new version and let me know if it is still a problem?

**Comment by SH-EDI** [comment]
I am now able to save the config file so at least this is saving me some time when I retry to see if it is fixed. 
I installed the updated version but when I try to Create Visio it is still erroring for me.
I'm attaching the error messages and Details file in the hope you can help me to resolve this.
[Error Log - ERD Visio Creator.docx](https://github.com/LinkeD365/ERDVisioBuilder/files/6070099/Error.Log.-.ERD.Visio.Creator.docx)

**Comment by LinkeD365** [comment]
Hey @SH-EDI think I will need your help to resolve this, as in do a screen share and try to create your visio in debug mode?

**Comment by SH-EDI** [comment]
Hi,
Thank you for getting back to me and re-opening the case.
I'm not sure I have access to switch on debugger but if you can help with that then yes we can have a screen share.
I'll be out of the office until next Tuesday 9th March so let me know what time suits you and we can get something set up.
Susan

Susan Harkin
Data & Info Designer
Corporate Data Team

Mobile: 07443 876146
Phone: 0131 3706303
Upcoming leave: 08/03, 15/03, 22/03/2021

Great Data & Information - by Design
Digital Directorate - Digitally enabling Scottish Water


Scottish Water - Trusted to Serve Scotland

**Comment by SH-EDI** [comment]
Thank you for your help in resolving this issue.  I have now managed to generate the ERD visio file for our Dynamics application which is a huge step forward.
Many thanks also for getting the fix to me so quickly.
