### ISSUE TITLE
no FK tables (1:M or M:M) are included on visio file (the previous version worked fine)

### ISSUE THREAD

**Issue by popemot** [LinkeD365/ERDVisioBuilder#24]
today i download the newest version, I cannot create 1:M or M:M relationship diagrams as before

![image](https://user-images.githubusercontent.com/51127398/123840725-b0782280-d8dc-11eb-939d-018831c270ba.png)

visio output content
![image](https://user-images.githubusercontent.com/51127398/123840762-bff76b80-d8dc-11eb-9484-5a4265d5dcf0.png)

with the previous version, with the same configuration, the visio file created contained several entities and their relationships.

![image](https://user-images.githubusercontent.com/51127398/123840997-0a78e800-d8dd-11eb-811d-bcc424c98f77.png)

there is another way to do this or is a bug?

**Comment by LinkeD365** [comment]
Damn it. Fix something break something. Will check. Thanks for raising

**Comment by LinkeD365** [comment]
@popemot please check 6.2

**Comment by popemot** [comment]
@LinkeD365  thanks! it works fine with the new version!
have a good week!
