### ISSUE TITLE
Tool fails with "Sequence contains no matching elements"

### ISSUE THREAD

**Issue by dirasmitabasu** [LinkeD365/ERDVisioBuilder#27]
Whenever I try to create an ERD, I get the below message. I have Visio installed and am connected to CRM.
![image](https://user-images.githubusercontent.com/48103480/134415780-36db984c-19d6-4c38-9420-995fa50586d2.png)

**Comment by LinkeD365** [comment]
Hey @dirasmitabasu, there was an issue with solutions, which should be resolved in latest version, can you check now? If not, lets do a teams call & we can check it out together
