### ISSUE TITLE
Just found XRM Toolbox would like to use this tool but I'm getting runtime error

### ISSUE THREAD

**Issue by JamesAtTechAssistEnt** [LinkeD365/ERDVisioBuilder#43]
![image](https://github.com/LinkeD365/ERDVisioBuilder/assets/51051781/f4e43856-f2dd-4480-a586-b2519bde0df8)

I just found this tool in the XRM Toolbox. I have been using the Power Automate to Visio tool quite effectively as well as some of the Solution tools. But I can't figure out how to get past this error. Any assistance would be greatly appreciated.

**Comment by jamehealy** [comment]
Yeah, I'm getting the same. I'll let you know if I figure it out!

**Comment by LinkeD365** [comment]
Hey both, this should be resolved by getting the latest version of XrmToolBox. There were some big changes in the last one. If that doesn't work, uninstall and start again.

The latest version of tool is up to date with latest version of XTB
