### ISSUE TITLE
Save Settings - Enhancement Request

### ISSUE THREAD

**Issue by DiggaTheWolf** [LinkeD365/ERDVisioBuilder#7]
It would be really nice to be able to save and load settings from a previous session, rather than having to create from scratch again.

**Comment by LinkeD365** [comment]
What bits do you want saving @DiggaTheWolf ? Everything including Entity selection or just the options you choose?

**Comment by DiggaTheWolf** [comment]
I would want everything to be honest. Additionally, a prompt about the overwriting of an existing Visio and settings file if that's possible.
